"""Template-driven codegen for staging models (GCC pattern: same map → same bytes).

dbt/sdis_maps/<model>.yml is the only thing the Surgeon edits. This module renders:
  * dbt/models/staging/<model>.sql   (explicit casts, load gate, dedupe)
  * dbt/models/staging/<model>.yml   (enforced contract + tests)
CI runs `sdis codegen --check` so hand edits to generated files fail the build.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

HEADER = "-- GENERATED by `sdis codegen` from dbt/sdis_maps/{model}.yml. Do not hand-edit."


def load_map(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _col_expr(c: dict[str, Any]) -> str:
    expr = c.get("expr") or c["source"]
    return f"cast({expr} as {c['type']})"


def render_sql(m: dict[str, Any]) -> str:
    cols = m["columns"]
    src = m["source"]
    lines = [HEADER.format(model=m["model"]), ""]
    lines.append("with source as (")
    lines.append(f"    select * from {{{{ source('{src['name']}', '{src['table']}') }}}}")
    lines.append(f"    where {{{{ sdis_load_gate('{src['table']}') }}}}")
    lines.append("),")
    lines.append("")
    lines.append("mapped as (")
    lines.append("    select")
    # one column per line, no alignment padding → a remediation diff touches exactly one line
    for c in cols:
        lines.append(f"        {_col_expr(c)} as {c['alias']},")
    lines.append("        _LOAD_ID as _load_id,")
    lines.append("        _LOADED_AT as _loaded_at")
    lines.append("    from source")
    lines.append(")")
    lines.append("")
    lines.append("select * from mapped")
    key = m.get("dedupe_key")
    if key:
        lines.append(f"qualify row_number() over (partition by {key} order by _loaded_at desc, _load_id desc) = 1")
    return "\n".join(lines) + "\n"


def _yml_columns(cols: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out = []
    for c in cols:
        entry: dict[str, Any] = {"name": c["alias"], "data_type": c["type"]}
        if c.get("description"):
            entry["description"] = c["description"]
        if c.get("tests"):
            entry["data_tests"] = list(c["tests"])
        meta: dict[str, Any] = {}
        if c.get("source"):
            meta["sdis_source_column"] = c["source"]
        if c.get("expr"):
            meta["sdis_expr"] = c["expr"]
        if meta:
            entry["config"] = {"meta": meta}
        out.append(entry)
    out.append({"name": "_load_id", "data_type": "varchar"})
    out.append({"name": "_loaded_at", "data_type": "timestamp_ltz"})
    return out


def render_yml(m: dict[str, Any]) -> str:
    model: dict[str, Any] = {
        "name": m["model"],
        "description": m.get("description", ""),
        "config": {"contract": {"enforced": True},
                   "meta": {"sdis_generated": True, "sdis_source": f"{m['source']['name']}.{m['source']['table']}"}},
        "columns": _yml_columns(m["columns"]),
    }
    doc = {"version": 2, "models": [model]}
    return (f"# GENERATED by `sdis codegen` from dbt/sdis_maps/{m['model']}.yml — do not hand-edit.\n"
            + yaml.safe_dump(doc, sort_keys=False, width=120))


def outputs_for(map_path: Path, staging_dir: Path) -> dict[Path, str]:
    m = load_map(map_path)
    return {
        staging_dir / f"{m['model']}.yml": render_yml(m),
        staging_dir / f"{m['model']}.sql": render_sql(m),
    }


def run(dbt_dir: Path, check: bool = False) -> list[str]:
    """Render all maps. With check=True, return the list of stale files instead of writing."""
    staging = dbt_dir / "models" / "staging"
    stale: list[str] = []
    for mp in sorted((dbt_dir / "sdis_maps").glob("*.yml")):
        expected = outputs_for(mp, staging)
        for path, content in expected.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(str(path))
                if not check:
                    path.write_text(content, encoding="utf-8", newline="\n")
    return stale
