"""Surgeon — minimal, reviewable dbt fix as a GitHub PR; merges only when policy allows.

States (re-entrant across heartbeats):
  no PR yet         → worktree → patch maps → codegen → commit → push → PR
  PR open, waiting  → SEV1/SEV2: request human approval (Paperclip confirmation)
                      SEV3/SEV4 + auto_merge_when_green: wait for CI
  approved + green  → merge → hand to Auditor
"""
from __future__ import annotations

import re

from .. import surgeon as patcher
from ..context import Context, Task
from ..models import AgentOutput, decision
from ..report import headline, markdown

AGENT = "surgeon"


def _pr_number(url: str | None) -> int | None:
    m = re.search(r"/pull/(\d+)", url or "")
    return int(m.group(1)) if m else None


def handle(ctx: Context, task: Task) -> AgentOutput:
    inc = task.incident_id
    d = ctx.wh.decision(inc)
    row = ctx.wh.incident(inc) or {}
    out = AgentOutput(agent=AGENT, run_id=ctx.tracer.run_id, status="success", incident_id=inc)
    confirmed = task.meta.get("confirmed") in (True, "true", "True")
    pr_url = row.get("PR_URL")

    with ctx.wh.for_incident(inc):
        if not pr_url:
            branch = patcher.branch_name(d)
            wt = ctx.github.worktree(branch)
            kw = {}
            if d.surgeon_action == "propose_breaking_remap":
                from ._inputs import analyze_load
                _, extras = analyze_load(ctx, d.table.split(".")[-1], None, d.load_id)
                kw = {"profiles": extras}
            if d.surgeon_action == "normalize_after_confirmation" or (d.top_class == "semantic" and confirmed):
                d.surgeon_action = "normalize_after_confirmation"
                kw = {"confirmed": confirmed}
            patch = patcher.build_patch(wt / "dbt", d, **kw)
            out.decisions.append(decision("patch", patch.action, "; ".join(patch.summary) or "no file changes",
                                          alternatives=["edit marts directly (rejected: aliases are the contract)"]))
            if patch.empty:
                ctx.github.drop_worktree(wt)
                out.status = "blocked"
                out.warnings += patch.needs_review_notes
                ctx.say(f"🔧 Surgeon    nothing safe to patch automatically: {patch.needs_review_notes}")
                return out
            notes = "\n".join(f"- ⚠️ {n}" for n in patch.needs_review_notes)
            extra = ("### Change\n" + "\n".join(f"- {s}" for s in patch.summary)
                     + (f"\n\n### Needs a human\n{notes}" if notes else "")
                     + "\n\n_Generated by the SDIS Surgeon agent. Only `dbt/sdis_maps/` and source docs were edited; "
                       "staging SQL is re-rendered by `sdis codegen`._")
            ctx.github.commit_and_push(wt, branch, patch.files,
                                       f"sdis({d.top_class}): {headline(d)}\n\nIncident {inc}")
            ctx.github.drop_worktree(wt)
            labels = ["sdis", f"drift:{d.top_class}", d.severity.lower()] + (["needs-human"] if d.requires_human_approval else [])
            pr = ctx.github.open_pr(branch, f"[{d.severity}] {headline(d)}",
                                    markdown(d, row.get("NARRATIVE"), extra), patch.draft, labels)
            pr_url = pr["html_url"]
            ctx.wh.update_incident(inc, pr_url=pr_url)
            out.artifacts.append({"type": "pull_request", "url": pr_url, "draft": patch.draft})
            ctx.say(f"🔧 Surgeon    PR opened{' (draft)' if patch.draft else ''}: {pr_url}")
            for s in patch.summary:
                ctx.say(f"   • {s}")

        number = _pr_number(pr_url)
        pr = ctx.github.pr(number)
        if pr.get("merged"):
            out.decisions.append(decision("merge", "already merged", "PR merged earlier"))
            return _handoff(ctx, task, d, out)

        approved = not d.requires_human_approval
        if d.requires_human_approval:
            state = ctx.approval(task.issue_id, f"merge-pr-{number}",
                                 f"{d.severity} {d.top_class} on {d.table.split('.')[-1]}: approve merging PR #{number}? "
                                 f"{pr_url}")
            out.decisions.append(decision("human_approval", state,
                                          f"{d.severity} is in human_approval_severities; approval requested in Paperclip"))
            if state != "accepted":
                out.status = "waiting" if state == "pending" else "blocked"
                out.next_steps.append("Waiting for human approval" if state == "pending" else "Approval rejected")
                return out
            approved = True
        elif not d.auto_merge_when_green:
            out.status = "waiting"
            out.next_steps.append("Playbook does not auto-merge; waiting for a reviewer")
            return out

        ci = ctx.github.ci_state(pr["head"]["sha"])
        out.decisions.append(decision("ci_gate", ci, "tests-before-merge: pytest + codegen check + dbt build"))
        if ci != "success":
            out.status = "waiting" if ci == "pending" else "blocked"
            ctx.say(f"   ⏳ CI is {ci}; will merge once green")
            return out
        ctx.github.merge(number, d.severity, approved, ctx.playbooks["human_approval_severities"])
        ctx.say(f"🔧 Surgeon    merged PR #{number}")
        return _handoff(ctx, task, d, out)


def _handoff(ctx: Context, task: Task, d, out: AgentOutput) -> AgentOutput:
    ctx.delegate(Task(agent="auditor", title=f"Verify & close {d.incident_id}", description=headline(d),
                      incident_id=d.incident_id, meta={"approved": "true"}), parent_issue_id=task.issue_id)
    out.next_steps.append("Auditor: verify, release gate, resolve")
    return out
