-- GENERATED by `sdis codegen` from dbt/sdis_maps/stg_customers.yml. Do not hand-edit.

with source as (
    select * from {{ source('raw', 'customers') }}
    where {{ sdis_load_gate('customers') }}
),

mapped as (
    select
        cast(CUST_ID as number(38,0)) as cust_id,
        cast(SEGMENT as varchar) as segment,
        cast(CITY as varchar) as city,
        cast(SIGNUP_DATE as date) as signup_date,
        _LOAD_ID as _load_id,
        _LOADED_AT as _loaded_at
    from source
)

select * from mapped
qualify row_number() over (partition by cust_id order by _loaded_at desc, _load_id desc) = 1
