-- GENERATED by `sdis codegen` from dbt/sdis_maps/stg_orders.yml. Do not hand-edit.

with source as (
    select * from {{ source('raw', 'orders') }}
    where {{ sdis_load_gate('orders') }}
),

mapped as (
    select
        cast(ORDER_ID as number(38,0)) as order_id,
        cast(CUST_ID as number(38,0)) as cust_id,
        cast(ORDER_TS as timestamp_ntz) as order_ts,
        cast(AMOUNT as number(10,2)) as amount_inr,
        cast(STATUS as varchar) as status,
        cast(CHANNEL as varchar) as channel,
        _LOAD_ID as _load_id,
        _LOADED_AT as _loaded_at
    from source
)

select * from mapped
qualify row_number() over (partition by order_id order by _loaded_at desc, _load_id desc) = 1
